"""Add subscription_expires_at column to users

The column was declared in the User model (backend/app/models/user.py) in commit
352f71b on 2026-04-10 as part of the Stripe subscription expansion, but the
matching migration was never written. The User SELECT generated by SQLAlchemy
references the column, so every query that touches users — including login —
crashes with "UndefinedColumnError: column users.subscription_expires_at does
not exist", breaking authentication site-wide.

This migration adds the missing column. It is NULLABLE (matches the model's
`Mapped[datetime | None]`) so existing rows take NULL without issue.

Revision ID: 007
Revises: 006
"""
from alembic import op
import sqlalchemy as sa


revision = "007"
down_revision = "006"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "users",
        sa.Column(
            "subscription_expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )


def downgrade():
    op.drop_column("users", "subscription_expires_at")
